### ISSUE TITLE
Handle deprecated CVP APIs

### ISSUE THREAD

**Issue by devrobo** [aristanetworks/cvprac#105]
These are deprecated in 2020.2

**/cvpservice/inventory**

POST /inventory/deleteDevices.do is marked as deprecated starting 2020.1. It is replaced by DELETE on /inventory/devices, available starting 2020.1.0.

**/cvpservice/provisioning (also available at /cvpservice/ztp)**

/provisioning/getconfigfortask is marked as deprecated starting 2020.2. It is replaced by /provisioning/v3/getconfigfortask, available starting (I think a long time ago, need to look up when)

/provisioning/v2/getconfigfortask is marked as deprecated starting 2020.2. It is replaced by /provisioning/v3/getconfigfortask, available starting (I think a long time ago, need to look up when).

/provisioning/runConfigSync.do is marked as deprecated starting 2020.2. It is replaced by /provisioning/checkCompliance.do, available starting (I think a long time ago, need to look up when).

/provisioning/validateAndCompareConfiglets.do is marked as deprecated start 2020.2. It is replaced by /provisioning/v2/validateAndCompareConfiglets.do, available starting (I think a long time ago, need to look up when).

**Comment by mharista** [comment]
The only API that needs to be addressed for cvprac is the POST to /inventory/deleteDevices.do.

The remaining APIs being deprecated are not used at all in cvprac currently or are already using the replacement API.
