### ISSUE TITLE
Time in approve_change_control is defaulted when script starts instead of when function is called

### ISSUE THREAD

**Issue by mharista** [aristanetworks/cvprac#162]

**Comment by shauryakatiyar** [comment]
Can this be fixed?

@mharista is there any workaround for this?

**Comment by mharista** [comment]
Hi @shauryakatiyar 

I will get this fixed as soon as possible. At the moment the only workaround would be to recreate the function without the timestamp instantiated in the function definition.

**Comment by mharista** [comment]
I tested a fix for this today. Will push the fix after the system tests complete. @shauryakatiyar the update will be available in the develop branch today and in the next release of cvprac which should be in the next couple of weeks.

**Comment by mharista** [comment]
Fixed 2b1e6ac44fbc912ea60841eb10ab2d19b1f59c65
