### ISSUE TITLE
addTempAction call required before saveTopology in newer releases.

### ISSUE THREAD

**Issue by mharista** [aristanetworks/cvprac#17]
When doing add and delete containers in 2016.1.2.1 the new version requires a 'provisioning/addTempAction.do' call before the '/provisioning/saveTopology.do' call, but the current methods only do the saveTopology.do.

**Comment by devrobo** [comment]
Hi Matt,
Do you mean 2016.2 i.e. Clearlake? I tested on 2016.1.2.1 and how are the
system tests passing? They add and delete a container.

John

**Comment by mharista** [comment]
Hi John,

I should have been more specific with the issue I am seeing on 2016.1.2.1. The container does get created but it never shows up on the network provisioning page even with saving and refreshing. The calls to add and delete do work so the system tests will still work. The container is also included when I get a list of all the containers in the system using the rest calls, so it appears to just be a bug in the GUI. Cheyne suggested trying to addTempAction before the saveTopology to see if that fixes the issue because that is what is being done in the python api.
