### ISSUE TITLE
Get request to CVaaS/on-prem CVP with Authorization bearer fails for getImageBundles.do

### ISSUE THREAD

**Issue by ankudinov** [aristanetworks/cvprac#182]
`getImageBundles.do` Get request to CVaaS/on-prem CVP fails with 503 error. The problem is CVaaS API bug, nevertheless I'd suggest to add additional controls to cvprac library. That is required for the new Ansible CVP cv_image_v3 module.

I'd suggest adding something like `token_auth_type = <bearer / cookie>` to the `connect` method.

**Comment by noredistribution** [comment]
Closing this as this was fixed in 2022.2.0+ and CVaaS 2 years ago
