### ISSUE TITLE
Bug: Invalid `requests` version required in cvprac v1.2.2

### ISSUE THREAD

**Issue by ClausHolbechArista** [aristanetworks/cvprac#237]
In `requirements.txt` for v1.2.2 it says `requests>=1.0.0, <=2.27.1`, but as seen in issue #233 import fails unless `requests>=2.27.0`. Requirements should be updated or code should be changed to not rely on this version.

**Comment by mharista** [comment]
This is fixed in develop now and will be resolved in the next release.

**Comment by mharista** [comment]
Fixed in new release v1.3.0

**Comment by ClausHolbechArista** [comment]
> Fixed in new release v1.3.0

Thank you @mharista
