### ISSUE TITLE
Python2 is not supported anymore

### ISSUE THREAD

**Issue by asibiriakov** [aristanetworks/cvprac#266]
In Requirements could you make sure a right python version is mentioned. It still says Python2 is supported which is incorrect. Some issues I hit while trying to use it with python2:

No module:

ImportError: No module named JSONDecodeError

Failing at f-strings:

err_str = f"{err_str[:300]}[... truncated ...]" \

**Comment by mharista** [comment]
I plan to have this resolved in the next release.
