### ISSUE TITLE
escape data in parameters passed to CVP

### ISSUE THREAD

**Issue by jerearista** [aristanetworks/cvprac#47]
"Special" characters in request parameters may cause unexpected results from API calls.  In the API methods, we need  to escape these.

Example: If the container name has HTTP special characters like `Rack2+_DC11`:

```
    import urllib
    container_name = urllib.quote_plus(name)
    print("Encoded name: "+pformat(container_name))
    # Encoded name: 'Rack2%2B_DC11'

    CVP.get('/provisioning/searchTopology.do?queryParam=%s'
            '&startIndex=0&endIndex=0' % urllib.quote_plus(name))
```

Sample location:
 https://github.com/aristanetworks/cvprac/blob/2b26d0cff773ff687e0d7c0460dd64c9927f2383/cvprac/cvp_api.py#L324

**Comment by nicoduck** [comment]
This also results in Probems when creating new configlets with special characters in it.
The configlet is created properly but the GET automated request afterwards (to get the ID) fails because of the missing quotation.
