### ISSUE TITLE
Issue using cvprac in Python 3

### ISSUE THREAD

**Issue by DimitriCapetz** [aristanetworks/cvprac#60]
I am attempting to use cvprac in a Python 3 (specifically python 3.6.5) and when doing so, I receive the error below.  I do not receive this error when running the same script in Python 2.

`Traceback (most recent call last):
  File "cvp_test.py", line 12, in <module>
    switch_configlet_data = cvp.api.get_configlet_by_name('BGP route-maps and prefix-lists')
  File "/data/data/com.termux/files/home/test/test/lib/python3.6/site-packages/cvprac/cvp_api.py", line 214, in get_configlet_by_name
    % urllib.quote_plus(name),
AttributeError: module 'urllib' has no attribute 'quote_plus'`

For reference, here is my simple script.

`import cvprac.cvp_client

cvps = ['10.2.0.203']
cvp_username = 'cvpadmin'
cvp_password = 'password'

cvp = cvprac.cvp_client.CvpClient(syslog=True, filename='cvprac_log')
cvp.connect(cvps, cvp_username, cvp_password)

switch_configlet_data = cvp.api.get_configlet_by_name('BGP route-maps and prefix-lists')

print switch_configlet_data`

**Comment by packetferret** [comment]
check out this PR to see if it helps you out @DimitriCapetz, https://github.com/aristanetworks/cvprac/pull/69/files

**Comment by DimitriCapetz** [comment]
Hey!  Thanks for the info.  I checked out the PR and it worked beautifully in my (very minor) testing. Thanks for bringing my attention to it.  I'll work with this in my dev environment until it's officially pulled in.  Thanks again!

**Comment by mharista** [comment]
Hi @DimitriCapetz,

I just merged changes into develop that should cover this issue. I plan to cut a new release including this after a bit more testing with Python3.
