### ISSUE TITLE
CVP2018.2 support

### ISSUE THREAD

**Issue by cheynearista** [aristanetworks/cvprac#66]
Some APIs changed with CVP2018.2. These will need to be addressed.

**Comment by kwilliams312** [comment]
+1 to this, Any update on when the new CVPRAC will reflect the current api model?  Many basic things are currently broken.

**Comment by kwilliams312** [comment]
@mharista please help?! :)

**Comment by mharista** [comment]
Hi @kwilliams312,

Should be done this week. Mostly done now. Just working on tests and return data consistency where possible.

**Comment by mharista** [comment]
Fixed ad7b576758f6c8aaa839301ca68b4669ac377239

**Comment by mharista** [comment]
Additional issues may arise from this. Return data for some API's is the biggest issue. The commit referenced addresses many of these issues for inventory, configlets and containers, but that doesn't mean every possible return parameter for every API is consistent. All of our existing tests are passing for 2018.2 and previous versions.

If issues arise with individual APIs return data discrepancies then these should be addressed in specific issues.
