### ISSUE TITLE
User is unauthorized on get_devices_in_container

### ISSUE THREAD

**Issue by Drums090** [aristanetworks/cvprac#72]
On one method, I get the following:
{"errorCode":"112498","errorMessage":"Failure - User is unauthorized"}

The rest of the API calls in my script are working fine but for some reason this one is getting an authorization failure with the same credentials.

**Comment by mharista** [comment]
Hi @Drums090,

I have so far not been able to recreate this issue. What version of CVP are you running and what version of cvprac do you have installed?

**Comment by Drums090** [comment]
I am using the newest CVP release and pulled the CVPRAC folder after the
latest API update.

Regards,
Brandon Greer, CCNP
