### ISSUE TITLE
Convert README.md to README.rst for better pypi formating

### ISSUE THREAD

**Issue by cheynearista** [aristanetworks/cvprac#9]
The documentation **_format_** for cvprac on https://pypi.python.org/pypi/cvprac is hideous. It's plain ASCII. Would be nice to convert README.md to RestructuredTEXT, and modify setup.py to pull in as part of long_description. Subsequent package pushes to pypi would pull in modified/updated README.rst and doc format on https://pypi.python.org/pypi/cvprac would look more professional.

**Comment by phil-dileo** [comment]
You can technically do both.  You can keep your README.md, then have docs/readme.rst, then in your setup.py

```
with open(path.join(here, 'docs/description.rst'), encoding='utf-8') as f:
        long_description = f.read()

with open(path.join(here, 'VERSION'), mode='r', encoding='utf-8') as version_file:
        version = version_file.read().strip()

setup(
    name='pyeapi',

    # Versions should comply with PEP440.  For a discussion on single-sourcing
    # the version across setup.py and the project code, see
    # https://packaging.python.org/en/latest/single_source_version.html
    version=version,

    description='Python Client for eAPI',
    long_description=long_description,
...
```

And pypi will use the long desc.


Ref: https://github.com/arista-eosplus/pyeapi/blob/develop/setup.py

**Comment by cheynearista** [comment]
True...but then you're keeping up with two sets of doc and having to keep them in sync...right?
-c

**Comment by phil-dileo** [comment]
Kind of. Typically the pypi landing page is a quick description which would punt you to readthedocs.  I think that's why it'll use long description when present.
