### ISSUE TITLE
Add return option to - def cancel_task(self, task_id):

### ISSUE THREAD

**Issue by Hugh-Adams** [aristanetworks/cvprac#98]
For the function "def cancel_task(self, task_id):" can we add a return option for the API call. The code would look like:

**return** self.clnt.post('/task/cancelTask.do', data=data,timeout=self.request_timeout)

instead of 

self.clnt.post('/task/cancelTask.do', data=data, timeout=self.request_timeout)

This allows calling scripts to access the success/error messages returned by the API call.

**Comment by mharista** [comment]
Fixed 2356d59e0e0fb9db2de9e8b3f123ad31c97e5cf7
