### ISSUE TITLE
Deprecate support for various APIs in 2019.x

### ISSUE THREAD

**Issue by cheynearista** [aristanetworks/cvprac#99]
Several APIs being removed in 2019.x. Need to make sure these are deprecated: 

   POST /cvpservice/changeControl/addOrUpdateChangeControl.do
   POST /cvpservice/changeControl/executeCC.do
   GET /cvpservice/changeControl/getTasksByStatus.do
   POST /cvpservice/changeControl/addNotesToChangeControl.do
   GET /cvpservice/changeControl/getChangeControls.do 
   GET /cvpservice/changeControl/getChangeControlInformation.do
   POST /cvpservice/changeControl/cancelChangeControl.do
   POST /cvpservice/changeControl/deleteChangeControls.do

**Comment by grybak-arista** [comment]
The v1 api issue should be addressed by #95. It doesn't cover the deprecations, though.

**Comment by cheynearista** [comment]
@grybak-arista Yeah...#95 fixes support for 2019.x. Changing the issue to relate to deprecated methods.

**Comment by mharista** [comment]
Handling of these API endpoints was taken care of in release v1.0.2
